# To be deleted: Not needed anymore since we are switching to Docusaurus versioning.

# # This workflow takes the current 'main' branch and updates the 'website-prod' branch with its contents.
# # This will trigger Cloudflare to publish a new version of the website.

# # NOTE: DO NOT make PRs against the website-prod branch.
# # Any changes here will be overwritten automatically in the next release.

# # Avoid running this workflow manually, as it is intended to be run only after a new release is published.
# # Running it manually can cause preview cmdlets and instructions to be published to the main version.

# name: publish-website

# on:
#   # Runs whenever a new Maester module is published
#   release:
#     types: [published]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# permissions:
#   contents: write

# jobs:
#   update-branch:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v6.0.0

#       - name: Update website-prod branch
#         run: |
#           git push origin --delete website-prod || true
#           git checkout -b website-prod
#           git push origin website-prod
