# Updates the maester-tests repository with the latest tests
# This is still required since we use it for the GitHub action and Azure DevOPs starter guide.
name: publish-tests

on:
  # Runs whenever a new Maester module is published
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - name: Publish to maester-tests
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@target-branch
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: ./tests
          target-directory: ./tests
          destination-github-username: "maester365"
          destination-repository-name: "maester-tests"
          user-email: merill@users.noreply.github.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main
