name: update-module-docs

on:
  push:
    branches:
      - main
    paths:
      - "powershell/**"
      - "!powershell/Maester.psd1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-command-reference:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
      - name: Update maester.dev powershell docs
        run: ./build/Update-CommandReference.ps1
        shell: pwsh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update maester.dev powershell docs
